server:
  port: 9002

spring:
  application:
    name: turbine-9002

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

turbine:
  app-config: MICROSERVICECLOUD-DEPT
  cluster-name-expression: "microservicecloud-dept"
  combine-host-port: true


